### ISSUE TITLE
Refacto process.commons.Publication

### ISSUE THREAD

**Issue by zacharyarnaise** [loicsteinmetz/alternbot-app#100]
Je pense que la classe `process.commons.Publication` mértirait d'être refactorisée.

À mon sens, on devrait seulement exposer les méthodes `sendMessage` et `sendFile`, le reste des méthodes devrait être passé en `private`
Dans ce cas, on pourrait remplacer l'unique appel à `sendLongMessage` directement par la seule instruction qu'elle contient:
https://github.com/B4va/alternbot-app/blob/17fe288fa3a2cc2e73f5848518f3d4ca6eebe5ad/src/main/java/process/commons/Publication.java#L43 https://github.com/B4va/alternbot-app/blob/17fe288fa3a2cc2e73f5848518f3d4ca6eebe5ad/src/main/java/process/commons/Publication.java#L86-L88

-----

Les méthodes suivantes pourraient être fusionnés en une seule:
```java
// Vérifie l’existence d'un channel sur un serveur
private boolean hasChannel(Guild guild, String channel);
// Crée un channel sur un serveur
private boolean createChannel(Guild guild, String channel);
// Renvoie un objet TextChannel si un channel est trouvé sur le serveur donné, sinon renvoie null
private TextChannel getChannel(Guild guild, String channel);
```

Actuellement, on vérifie deux fois de suite que le channel existe. Une fois dans les fonctions `sendMessage` et `sendFile` en appelant `hasChannel` et une autre fois dans les méthodes privées `doSendMessage` et `doSendFile` en appelant `getChannel` et en comparant son résultat avec `null`.

Je propose d'implémenter cette unique méthode en remplacement:
```java
private TextChannel getOrCreateChannel(Guild guild, String channel, boolean createIfNotExists);

// Vérifie l’existence d'un channel sur un serveur
isNull(getOrCreateChannel(guild, "super-channel", false));
// Crée un channel sur un serveur
getOrCreateChannel(guild, "super-channel", true);
// Renvoie un objet TextChannel si un channel est trouvé sur le serveur donné, sinon renvoie null
getOrCreateChannel(guild, "super-channel", false);
```

Ces changements permettraient d'alléger le code et les tests associés.

**Comment by B4va** [comment]
Je partage l'analyse, bien vu ;)
